services:
  - type: web
    name: payloca
    runtime: node
    buildCommand: pnpm install --no-frozen-lockfile && pnpm run build
    startCommand: pnpm run start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: PNPM_HOME
        value: /opt/render/.pnpm
