import { Router, type IRouter } from "express";
import healthRouter from "./health";
import annoncesRouter from "./annonces";
import messagingRouter from "./messaging";
import storageRouter from "./storage";
import pushTokensRouter from "./pushTokens";
import authRouter from "./auth";
import membershipRouter from "./membership";
import callsRouter from "./calls";
import servicesRouter from "./services";
import jobsRouter from "./jobs";
import userRouter from "./user";
import feedRouter from "./feed";
import socialRouter from "./social";
import streaksRouter from "./streaks";
import funRouter from "./fun";
import giftsRouter from "./gifts";
import referralsRouter from "./referrals";

const router: IRouter = Router();

router.use(healthRouter);
router.use(annoncesRouter);
router.use(messagingRouter);
router.use(storageRouter);
router.use(pushTokensRouter);
router.use(authRouter);
router.use(membershipRouter);
router.use(callsRouter);
router.use(servicesRouter);
router.use(jobsRouter);
router.use(userRouter);
router.use(feedRouter);
router.use(socialRouter);
router.use(streaksRouter);
router.use(funRouter);
router.use(giftsRouter);
router.use(referralsRouter);

export default router;
